"""關卡資料：敵機波次腳本與頭目設定。"""

from __future__ import annotations


def wave(t: float, kind: str, *, count: int = 1, gap: float = 0.35,
         pattern: str = "down", params: dict | None = None,
         x: float | None = None, xs: list[float] | None = None,
         y: float = -0.06, reward: str | None = None,
         side: str | None = None) -> dict:
    """建立一組波次資料。

    * ``x`` / ``xs`` 為畫面寬度比例（0.0 ~ 1.0）。
    * ``reward`` 為整組敵機全滅時掉落的道具種類。
    * ``side`` 為 ``left`` / ``right`` 時，敵機由畫面側邊進場。
    """
    return {
        "t": t, "kind": kind, "count": count, "gap": gap,
        "pattern": pattern, "params": params or {},
        "x": x, "xs": xs, "y": y, "reward": reward, "side": side,
    }


# --------------------------------------------------------------------------
STAGES: list[dict] = [
    # ---------------------------------------------------------------- 1
    {
        "name": "MIDWAY SEA",
        "subtitle": "太平洋・中途島海域",
        "theme": "ocean",
        "scroll": 72.0,
        "music": "stage1",
        "hp_scale": 1.0,
        "speed_scale": 1.0,
        "bullet_speed": 0.85,
        "boss": {"hp": 190, "score": 20000, "name": "AYAKO 超重爆"},
        "waves": [
            wave(1.5, "scout", count=5, gap=0.30, pattern="sine",
                 params={"amp": 60, "freq": 1.8}, x=0.25),
            wave(4.0, "scout", count=5, gap=0.30, pattern="sine",
                 params={"amp": 60, "freq": 1.8, "phase": 3.14}, x=0.75),
            wave(7.5, "red", count=4, gap=0.28, pattern="sine",
                 params={"amp": 90, "freq": 1.4}, x=0.5, reward="power"),
            wave(11.0, "scout", count=6, gap=0.22, pattern="dive", x=0.15, reward="wing"),
            wave(11.4, "scout", count=6, gap=0.22, pattern="dive", x=0.85),
            wave(16.0, "green", count=3, gap=0.6, pattern="hover",
                 params={"hold_y": 150, "hold_time": 3.0}, xs=[0.25, 0.5, 0.75]),
            wave(22.0, "red", count=5, gap=0.25, pattern="arc",
                 params={"radius": 110, "omega": 1.4, "drift": 40},
                 x=0.3, reward="wing"),
            wave(27.0, "bomber", count=2, gap=1.2, pattern="down", xs=[0.35, 0.65],
                 reward="laser"),
            wave(19.0, "destroyer", count=1, pattern="down", x=0.30, y=-0.22),
            wave(30.0, "destroyer", count=1, pattern="down", x=0.72, y=-0.22,
                 reward="bomb"),
            wave(32.0, "scout", count=8, gap=0.18, pattern="sine",
                 params={"amp": 100, "freq": 2.0}, x=0.5),
            wave(37.0, "green", count=4, gap=0.4, pattern="swoop",
                 params={"hold_y": 160, "dir": 1}, x=0.2, reward="power"),
            wave(42.0, "bomber", count=3, gap=0.9, pattern="sine",
                 params={"amp": 70, "freq": 1.0}, xs=[0.3, 0.5, 0.7], reward="wing"),
        ],
    },
    # ---------------------------------------------------------------- 2
    {
        "name": "CORAL ISLES",
        "subtitle": "珊瑚群島・低空突入",
        "theme": "islands",
        "scroll": 88.0,
        "music": "stage2",
        "hp_scale": 1.15,
        "speed_scale": 1.08,
        "bullet_speed": 0.95,
        "boss": {"hp": 300, "score": 30000, "name": "SHINDEN 空中要塞"},
        "waves": [
            wave(1.5, "red", count=6, gap=0.24, pattern="sine",
                 params={"amp": 80, "freq": 2.0}, x=0.3, reward="power"),
            wave(5.5, "jet", count=5, gap=0.22, pattern="dive", x=0.7, reward="wing"),
            wave(9.0, "green", count=4, gap=0.35, pattern="zigzag",
                 params={"period": 0.8, "dir": 1}, x=0.2),
            wave(9.4, "green", count=4, gap=0.35, pattern="zigzag",
                 params={"period": 0.8, "dir": -1}, x=0.8),
            wave(14.0, "scout", count=6, gap=0.2, pattern="sidesweep",
                 params={"dir": 1, "amp": 70}, side="left", y=0.18),
            wave(14.4, "scout", count=6, gap=0.2, pattern="sidesweep",
                 params={"dir": -1, "amp": 70}, side="right", y=0.30),
            wave(19.0, "bomber", count=3, gap=0.8, pattern="hover",
                 params={"hold_y": 140, "hold_time": 3.2}, xs=[0.25, 0.5, 0.75],
                 reward="laser"),
            wave(12.0, "destroyer", count=2, gap=3.0, pattern="down",
                 xs=[0.26, 0.74], y=-0.24),
            wave(31.0, "cruiser", count=1, pattern="down", x=0.5, y=-0.28,
                 reward="bomb"),
            wave(25.0, "red", count=5, gap=0.22, pattern="dive", x=0.5, reward="bomb"),
            wave(29.0, "jet", count=8, gap=0.16, pattern="sine",
                 params={"amp": 120, "freq": 2.4}, x=0.5),
            wave(34.0, "green", count=5, gap=0.4, pattern="swoop",
                 params={"hold_y": 180, "dir": -1}, x=0.85, reward="wing"),
            wave(39.0, "heavy", count=1, pattern="hover",
                 params={"hold_y": 130, "hold_time": 6.0}, x=0.5),
            wave(41.0, "jet", count=6, gap=0.2, pattern="dive", x=0.2, reward="wing"),
            wave(43.0, "jet", count=6, gap=0.2, pattern="dive", x=0.8),
        ],
    },
    # ---------------------------------------------------------------- 3
    {
        "name": "NIGHT RUN",
        "subtitle": "夜間強襲・無月之海",
        "theme": "night",
        "scroll": 96.0,
        "music": "stage3",
        "hp_scale": 1.3,
        "speed_scale": 1.15,
        "bullet_speed": 1.05,
        "boss": {"hp": 420, "score": 40000, "name": "KUROTSUKI 夜戰母機"},
        "waves": [
            wave(1.5, "jet", count=6, gap=0.18, pattern="sine",
                 params={"amp": 110, "freq": 2.6}, x=0.5, reward="power"),
            wave(5.5, "green", count=6, gap=0.3, pattern="dive", x=0.25, reward="wing"),
            wave(6.0, "green", count=6, gap=0.3, pattern="dive", x=0.75),
            wave(11.0, "bomber", count=4, gap=0.7, pattern="sine",
                 params={"amp": 90, "freq": 1.2}, xs=[0.2, 0.4, 0.6, 0.8],
                 reward="laser"),
            wave(16.0, "red", count=6, gap=0.2, pattern="arc",
                 params={"radius": 130, "omega": 1.7, "drift": 50}, x=0.35, reward="wing"),
            wave(21.0, "jet", count=8, gap=0.15, pattern="sidesweep",
                 params={"dir": 1, "amp": 90, "freq": 2.6}, side="left", y=0.22),
            wave(21.5, "jet", count=8, gap=0.15, pattern="sidesweep",
                 params={"dir": -1, "amp": 90, "freq": 2.6}, side="right", y=0.36),
            wave(27.0, "heavy", count=2, gap=1.6, pattern="hover",
                 params={"hold_y": 150, "hold_time": 5.0}, xs=[0.3, 0.7],
                 reward="vulcan"),
            wave(33.0, "green", count=8, gap=0.25, pattern="zigzag",
                 params={"period": 0.6}, x=0.5, reward="bomb"),
            wave(38.0, "bomber", count=4, gap=0.6, pattern="swoop",
                 params={"hold_y": 200, "dir": 1}, x=0.15, reward="wing"),
            wave(43.0, "jet", count=10, gap=0.14, pattern="dive", x=0.5, reward="roll"),
            wave(14.0, "destroyer", count=2, gap=4.0, pattern="down",
                 xs=[0.22, 0.78], y=-0.24),
            wave(30.0, "carrier", count=1, pattern="down", x=0.5, y=-0.32,
                 reward="wing"),
        ],
    },
    # ---------------------------------------------------------------- 4
    {
        "name": "DESERT LINE",
        "subtitle": "沙漠前線・敵軍機場",
        "theme": "desert",
        "scroll": 104.0,
        "music": "stage4",
        "hp_scale": 1.5,
        "speed_scale": 1.2,
        "bullet_speed": 1.12,
        "boss": {"hp": 560, "score": 50000, "name": "SANDSTORM 陸上戰艦"},
        "waves": [
            wave(1.2, "green", count=6, gap=0.25, pattern="sine",
                 params={"amp": 100, "freq": 2.2}, x=0.3, reward="power"),
            wave(5.0, "jet", count=8, gap=0.16, pattern="dive", x=0.6, reward="wing"),
            wave(9.0, "bomber", count=4, gap=0.6, pattern="hover",
                 params={"hold_y": 160, "hold_time": 3.8}, xs=[0.2, 0.4, 0.6, 0.8]),
            wave(15.0, "red", count=7, gap=0.2, pattern="sine",
                 params={"amp": 130, "freq": 2.4}, x=0.5, reward="wing"),
            wave(20.0, "heavy", count=2, gap=1.4, pattern="sine",
                 params={"amp": 80, "freq": 0.9}, xs=[0.35, 0.65], reward="laser"),
            wave(26.0, "jet", count=10, gap=0.13, pattern="sidesweep",
                 params={"dir": 1, "amp": 110, "freq": 3.0}, side="left", y=0.20),
            wave(26.5, "jet", count=10, gap=0.13, pattern="sidesweep",
                 params={"dir": -1, "amp": 110, "freq": 3.0}, side="right", y=0.34),
            wave(33.0, "green", count=8, gap=0.28, pattern="swoop",
                 params={"hold_y": 190, "dir": -1}, x=0.9, reward="bomb"),
            wave(39.0, "bomber", count=5, gap=0.55, pattern="dive", x=0.5, reward="wing"),
            wave(44.0, "heavy", count=3, gap=1.1, pattern="hover",
                 params={"hold_y": 140, "hold_time": 4.5}, xs=[0.25, 0.5, 0.75]),
        ],
    },
    # ---------------------------------------------------------------- 5
    {
        "name": "IRON FORTRESS",
        "subtitle": "鋼鐵要塞・正面突破",
        "theme": "fortress",
        "scroll": 118.0,
        "music": "stage5",
        "hp_scale": 1.8,
        "speed_scale": 1.28,
        "bullet_speed": 1.2,
        "boss": {"hp": 780, "score": 80000, "name": "OMEGA 要塞核心"},
        "waves": [
            wave(1.2, "jet", count=10, gap=0.14, pattern="sine",
                 params={"amp": 120, "freq": 2.8}, x=0.5, reward="power"),
            wave(6.0, "green", count=8, gap=0.22, pattern="dive", x=0.2, reward="wing"),
            wave(6.4, "green", count=8, gap=0.22, pattern="dive", x=0.8),
            wave(12.0, "heavy", count=2, gap=1.2, pattern="hover",
                 params={"hold_y": 150, "hold_time": 5.5}, xs=[0.3, 0.7]),
            wave(18.0, "red", count=8, gap=0.18, pattern="arc",
                 params={"radius": 140, "omega": 2.0, "drift": 60}, x=0.4, reward="wing"),
            wave(23.0, "bomber", count=6, gap=0.5, pattern="sine",
                 params={"amp": 110, "freq": 1.5}, x=0.5, reward="laser"),
            wave(29.0, "jet", count=12, gap=0.12, pattern="sidesweep",
                 params={"dir": 1, "amp": 120, "freq": 3.2}, side="left", y=0.18),
            wave(29.4, "jet", count=12, gap=0.12, pattern="sidesweep",
                 params={"dir": -1, "amp": 120, "freq": 3.2}, side="right", y=0.32),
            wave(36.0, "green", count=10, gap=0.24, pattern="zigzag",
                 params={"period": 0.55}, x=0.5, reward="bomb"),
            wave(42.0, "heavy", count=3, gap=1.0, pattern="sine",
                 params={"amp": 90, "freq": 1.1}, xs=[0.25, 0.5, 0.75],
                 reward="vulcan"),
            wave(48.0, "bomber", count=6, gap=0.4, pattern="dive", x=0.5, reward="wing"),
        ],
    },
    # ---------------------------------------------------------------- 6
    {
        "name": "VOLCANIC RIM",
        "subtitle": "火山列島・熔岩地帶",
        "theme": "volcano",
        "scroll": 126.0,
        "music": "stage6",
        "hp_scale": 2.0,
        "speed_scale": 1.34,
        "bullet_speed": 1.26,
        "boss": {"hp": 950, "score": 100000, "name": "MAGMADON 熔岩機龍"},
        "waves": [
            wave(1.2, "red", count=10, gap=0.14, pattern="sine",
                 params={"amp": 130, "freq": 3.0}, x=0.5, reward="power"),
            wave(5.5, "jet", count=9, gap=0.16, pattern="dive", x=0.18, reward="wing"),
            wave(5.9, "jet", count=9, gap=0.16, pattern="dive", x=0.82),
            wave(11.0, "heavy", count=2, gap=1.1, pattern="hover",
                 params={"hold_y": 145, "hold_time": 5.0}, xs=[0.28, 0.72],
                 reward="laser"),
            wave(17.0, "green", count=10, gap=0.20, pattern="zigzag",
                 params={"period": 0.50, "dir": 1}, x=0.35),
            wave(17.4, "green", count=10, gap=0.20, pattern="zigzag",
                 params={"period": 0.50, "dir": -1}, x=0.65, reward="wing"),
            wave(23.0, "bomber", count=6, gap=0.45, pattern="arc",
                 params={"radius": 150, "omega": 2.0, "drift": 60}, x=0.4,
                 reward="bomb"),
            wave(29.0, "jet", count=12, gap=0.11, pattern="sidesweep",
                 params={"dir": 1, "amp": 130, "freq": 3.4}, side="left", y=0.16),
            wave(29.4, "jet", count=12, gap=0.11, pattern="sidesweep",
                 params={"dir": -1, "amp": 130, "freq": 3.4}, side="right", y=0.30),
            wave(35.5, "red", count=10, gap=0.18, pattern="swoop",
                 params={"hold_y": 200, "dir": 1}, x=0.12, reward="roll"),
            wave(41.0, "heavy", count=3, gap=0.95, pattern="sine",
                 params={"amp": 100, "freq": 1.2}, xs=[0.25, 0.5, 0.75]),
            wave(47.5, "bomber", count=7, gap=0.38, pattern="dive", x=0.5,
                 reward="wing"),
        ],
    },
    # ---------------------------------------------------------------- 7
    {
        "name": "FINAL SORTIE",
        "subtitle": "最終決戰・敵軍旗艦隊",
        "theme": "fleet",
        "scroll": 134.0,
        "music": "stage7",
        "hp_scale": 2.2,
        "speed_scale": 1.40,
        "bullet_speed": 1.32,
        "boss": {"hp": 1200, "score": 150000, "name": "SHIRANUI 超弩級旗艦"},
        "waves": [
            wave(1.2, "jet", count=12, gap=0.11, pattern="sine",
                 params={"amp": 135, "freq": 3.2}, x=0.5, reward="power"),
            wave(6.0, "heavy", count=2, gap=1.0, pattern="sine",
                 params={"amp": 95, "freq": 1.0}, xs=[0.3, 0.7], reward="vulcan"),
            wave(12.0, "red", count=10, gap=0.16, pattern="arc",
                 params={"radius": 150, "omega": 2.2, "drift": 65}, x=0.35,
                 reward="wing"),
            wave(17.5, "green", count=10, gap=0.20, pattern="dive", x=0.20),
            wave(17.9, "green", count=10, gap=0.20, pattern="dive", x=0.80,
                 reward="laser"),
            wave(23.5, "bomber", count=7, gap=0.42, pattern="hover",
                 params={"hold_y": 150, "hold_time": 4.0}, xs=[0.2, 0.4, 0.6, 0.8]),
            wave(30.0, "jet", count=14, gap=0.10, pattern="sidesweep",
                 params={"dir": 1, "amp": 135, "freq": 3.6}, side="left", y=0.15),
            wave(30.4, "jet", count=14, gap=0.10, pattern="sidesweep",
                 params={"dir": -1, "amp": 135, "freq": 3.6}, side="right", y=0.29),
            wave(37.0, "heavy", count=3, gap=0.9, pattern="hover",
                 params={"hold_y": 140, "hold_time": 5.0}, xs=[0.25, 0.5, 0.75],
                 reward="bomb"),
            wave(44.0, "red", count=12, gap=0.15, pattern="zigzag",
                 params={"period": 0.48}, x=0.5, reward="wing"),
            wave(50.0, "bomber", count=8, gap=0.35, pattern="sine",
                 params={"amp": 120, "freq": 1.6}, x=0.5),
            wave(55.0, "heavy", count=4, gap=0.85, pattern="dive", xs=[0.2, 0.4, 0.6, 0.8],
                 reward="wing"),
            # 敵軍主力艦隊
            wave(3.0, "destroyer", count=2, gap=5.0, pattern="down",
                 xs=[0.20, 0.80], y=-0.24),
            wave(15.0, "cruiser", count=2, gap=6.0, pattern="down",
                 xs=[0.30, 0.70], y=-0.28, reward="vulcan"),
            wave(28.0, "carrier", count=1, pattern="down", x=0.5, y=-0.34,
                 reward="power"),
            wave(41.0, "battleship", count=1, pattern="down", x=0.42, y=-0.34,
                 reward="laser"),
            wave(47.0, "battleship", count=1, pattern="down", x=0.62, y=-0.34,
                 reward="roll"),
        ],
    },
]

STAGE_COUNT = len(STAGES)
